standalone_tags:
  [
    {id:    5, size: 0.02},
    {id:   10, size: 0.02, name: 'box'},
    {id:  413, size: 0.02},
    {id:  820, size: 0.02},
    {id:  875, size: 0.02},
    {id: 1050, size: 0.02}
  ]
